### ISSUE TITLE
panic: could not build `kencommandhandler`: ERR Client sent AUTH, but no password is set 

### ISSUE THREAD

**Issue by LiebesWavezLP** [zekroTJA/shinpuru#340]
### Type

Crash

### Instance

Selfhosted Binaries

### Description

Bots crashed when start on  version 1.28.0 binaries.

### Steps to reproduce

1. Download and setup the 1.28.0 binaries version of the bot
2. Config the bot
3. Start the bot

### Attachments

```
INFO[2022/01/16 13:54:29 CET] Starting up...                                                                            
INFO[2022/01/16 13:54:29 CET] Checking database for migrations and apply if needed...                                   
INFO[2022/01/16 13:54:29 CET] Enabled redis as database cache                                                          
INFO[2022/01/16 13:54:29 CET] Connected to database                                                                     
panic: could not build `kencommandhandler`: ERR Client sent AUTH, but no password is set                                                                                                                                                        
goroutine 1 [running]:                                                                                                  
github.com/sarulabs/di/v2.(*containerGetter).Get(0xd, 0x86d0e0, {0xfcd7b3, 0xc00009d570}) 
                   /home/runner/go/pkg/mod/github.com/sarulabs/di/v2@v2.4.2/containerGetter.go:17 +0x45                            
github.com/sarulabs/di/v2.(*container).Get(0xfbd142, {0xfcd7b3, 0x0})
                  /home/runner/go/pkg/mod/github.com/sarulabs/di/v2@v2.4.2/container.go:38 +0x2e                                  
main.main()                                                                                                                     
/home/runner/work/shinpuru/shinpuru/cmd/shinpuru/main.go:378 +0x13dc 
```

**Comment by zekroTJA** [comment]
This actually seems like a configuration failure with either your Redis instance or your redis connection configuration. Could you please provide your redis configuration in the shinpuru config file?

**Comment by LiebesWavezLP** [comment]
I have fixed it already i just found it out. but im woundering because i had set a password and never changed it.

i had changed:
```yaml
cache:
  redis:
    addr: "localhost:6379"
    password: "password"
    type: 0
  cachedatabase: true
```
to
```yaml
cache:
  redis:
    addr: "localhost:6379"
    type: 0
  cachedatabase: true
```
